---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    hibernate:
      ddl-auto: create-drop
  thymeleaf:
    cache: false
    spring:
      h2:
        console.enabled: true
logging:
  level:
    sql: debug
    web: debug
    tacos: debug
taco:
  orders:
    pageSize: 10
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    generate-unique-name: false
    name: tacoprod
logging:
  level:
    sql: WARN
    web: WARN
    tacos: WARN
