#spring:
#  datasource:
#    generate-unique-name: false
#    name: tacocloud
spring:
  data:
    cassandra:
      keyspace-name: taco_cloud
      schema-action: recreate
      local-datacenter: datacenter1
  thymeleaf:
    cache: false
#    spring:
#      h2:
#        console.enabled: true
