spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  jpa:
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
    spring:
      h2:
        console.enabled: true
  data:
    rest:
      base-path: /data-api
  security:
    enable-csrf: false
logging:
  level:
    sql: debug
    web: debug
    tacos: debug
taco:
  orders:
    pageSize: 10
